default_platform(:ios)

platform :ios do 
  lane :build_to_appcenter do 

    gym(scheme: "BrokerAppDemo",
    	  export_method: "enterprise")
       
    appcenter_upload(
      api_token: <API-TOKEN>,
      owner_name: "BCS-1",
      owner_type: "organization",
      app_name: "Oh-My-Broker",
      destinations: "Public",
      file: "Oh My Broker.ipa") 
  end
end
